### ISSUE TITLE
Text gets underlined automatically

### ISSUE THREAD

**Issue by vyshnav-vinod** [jakob-bagterp/colorist-for-python#313]
First of all, this library is what i was looking for and you have done an amazing job.

Recently, i found a bug in which the text gets automatically underlined

![Screenshot from 2024-04-28 10-43-32](https://github.com/jakob-bagterp/colorist-for-python/assets/154617184/32e3128f-dd84-4fe1-b288-31900da09e60)

In this screenshot you can see that, i have only used the BOLD effect and even turned it off, but after Effect.BOLD_OFF, somehow the rest of the text gets underlined. I need to use `Effect.OFF` after `Effect.BOLD_OFF` to remove this. This is kinda weird as before i tried this, i have a print function where i print the text in a color and also in bold and this issue doesnt happen.

**Comment by jakob-bagterp** [comment]
@vyshnav-vinod: Thank you for reporting. Are you using VS Code or something else?

If you use the standard terminal on a Mac, you get this...

<img width="219" alt="Screenshot 2024-04-29 at 23 46 59" src="https://github.com/jakob-bagterp/colorist-for-python/assets/25110864/05570c62-48ab-4d76-8baa-5f6d0d5b133d">

... based on the following example:

```python
from colorist import Effect

print(f"{Effect.BOLD}Hello{Effect.BOLD_OFF} this will be underlined")
print(f"{Effect.BOLD}Hello{Effect.OFF} this will be underlined")
```

Though the same code yields this in VS Code:

<img width="235" alt="Screenshot 2024-04-29 at 23 49 25" src="https://github.com/jakob-bagterp/colorist-for-python/assets/25110864/02043c28-a947-478b-8acc-f958f8f12fed">

To solve your issue quickly, suggest using `Effect.OFF` instead of `Effect.BOLD_OFF`. Would that work for you?

**Comment by vyshnav-vinod** [comment]
@jakob-bagterp Yes i am using Vscode. To fix that bug , i used the `Effect.OFF`. I just wanted to point out the bug :)
